/*
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.cjwizard.demo;

import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Image;
import java.util.List;
import javax.swing.JFrame;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AO
 */
public class Main extends javax.swing.JDialog {
    public static final String TITLE="CJ Wizard Demos";    //TODO i18n
    private final static Logger log = LoggerFactory.getLogger(Main.class);

    /**
     * Creates new form Main
     */
    public Main() {
        super(new DummyFrame(TITLE));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonDemo2 = new javax.swing.JButton();
        jButtonDemo1 = new javax.swing.JButton();
        jButtonNavBar = new javax.swing.JButton();
        jButtonNavBar1 = new javax.swing.JButton();
        jButtonNavBar2 = new javax.swing.JButton();
        jButtonNavBar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CJ Wizard Demos");

        jButtonDemo2.setText("Wizard Test 2");
        jButtonDemo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemo2ActionPerformed(evt);
            }
        });

        jButtonDemo1.setText("Wizard Test 1");
        jButtonDemo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemo1ActionPerformed(evt);
            }
        });

        jButtonNavBar.setText("Example Nav Bar");
        jButtonNavBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavBarActionPerformed(evt);
            }
        });

        jButtonNavBar1.setText("Nav bar with dynamic pages");
        jButtonNavBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavBar1ActionPerformed(evt);
            }
        });

        jButtonNavBar2.setText("Nav bar with complex worlflows");
        jButtonNavBar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavBar2ActionPerformed(evt);
            }
        });

        jButtonNavBar3.setText("Nav bar with complex worlflows 2");
        jButtonNavBar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavBar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDemo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 254, Short.MAX_VALUE))
                    .addComponent(jButtonDemo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNavBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNavBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNavBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDemo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDemo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavBar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavBar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavBar3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDemo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemo1ActionPerformed

        WizardTest test = new WizardTest();
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);

    }//GEN-LAST:event_jButtonDemo1ActionPerformed

    private void jButtonDemo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemo2ActionPerformed

        WizardTest2 test = new WizardTest2();
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);
    }//GEN-LAST:event_jButtonDemo2ActionPerformed

    private void jButtonNavBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavBarActionPerformed

        WizardTestNavBar test = new WizardTestNavBar(new javax.swing.JFrame(), true);
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);
    }//GEN-LAST:event_jButtonNavBarActionPerformed

    private void jButtonNavBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavBar1ActionPerformed

        WizardTest4ComplexNav test = new WizardTest4ComplexNav(new javax.swing.JFrame(), true);
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);
    }//GEN-LAST:event_jButtonNavBar1ActionPerformed

    private void jButtonNavBar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavBar2ActionPerformed

        com.github.cjwizard.demo.complex.ComplexNavMain test = new com.github.cjwizard.demo.complex.ComplexNavMain(new javax.swing.JFrame(), true);
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);
    }//GEN-LAST:event_jButtonNavBar2ActionPerformed

    private void jButtonNavBar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavBar3ActionPerformed

        com.github.cjwizard.demo.complex2.ComplexNavMain test = new com.github.cjwizard.demo.complex2.ComplexNavMain(new javax.swing.JFrame(), true);
        test.setSize(new Dimension(600, 300));
        test.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); // prevent user from doing something else
        test.setLocationRelativeTo(null);
        test.setVisible(true);
    }//GEN-LAST:event_jButtonNavBar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Main dialog = new Main();
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setTitle(TITLE);
                    dialog.pack();
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            log.warn(ex.getMessage(), ex);
        } catch (InstantiationException ex) {
            log.warn(ex.getMessage(), ex);
        } catch (IllegalAccessException ex) {
            log.warn(ex.getMessage(), ex);
        } catch (UnsupportedLookAndFeelException ex) {
            log.warn(ex.getMessage(), ex);
        }
    }

    /**
     * makes the jDialog show up in the task bar
     * see
     * https://stackoverflow.com/questions/8006502/show-jdialog-on-windows-taskbar
     */
    private static class DummyFrame extends JFrame {

        DummyFrame(String title) {
            super(title);
            setUndecorated(true);
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDemo1;
    private javax.swing.JButton jButtonDemo2;
    private javax.swing.JButton jButtonNavBar;
    private javax.swing.JButton jButtonNavBar1;
    private javax.swing.JButton jButtonNavBar2;
    private javax.swing.JButton jButtonNavBar3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
