language: java

jdk:
  #- openjdk7
  - openjdk8
  #- oraclejdk8
  - openjdk9
  #- oraclejdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
  
script:
  - mvn clean install
  - mvn site
  - mvn site:stage
